---

- name: Ensure jq is present
  ansible.builtin.package:
    name: jq
    state: present
  delegate_to: "{{ otelcol_server_ansible_host }}"

- name: Retrieve server access key
  ansible.builtin.shell:  # noqa no-changed-when
    cmd: |
      set -o pipefail
      curl -s -u "{{ openobserve_root_user_email }}:{{ openobserve_root_user_pass }}" http://localhost:5080/api/default/passcode | jq -r .data.passcode
  args:
    executable: /bin/bash
  delegate_to: "{{ otelcol_server_ansible_host }}"
  register: agent_auth_key
  changed_when: false
  no_log: "{{ otelcol_no_log | default(true) }}"

- name: Set fact auth key
  ansible.builtin.set_fact:
    otelcol_auth_key: "{{ agent_auth_key.stdout }}"
  no_log: "{{ otelcol_no_log | default(true) }}"
